version: '3'
services:
  bot:
    build: .
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d